d /var/lib/vera-updater 0710 root vera -
d /var/lib/vera-updater/requests 0750 vera vera -
d /var/lib/vera-updater/status 2750 root vera -
d /var/lib/vera-updater/backups 0700 root root -
d /var/lib/vera-updater/repository 0700 root root -
d /var/lib/vera-updater/npm-cache 0700 root root -
